# Generated by Django 5.0.7 on 2024-08-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='good',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='boardmodel',
            name='read',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='boardmodel',
            name='readtext',
            field=models.TextField(blank=True, default='name', null=True),
        ),
    ]
